# This is a basic workflow to help you get started with Actions

name: THE_WARZONE_REPORT_HOURLY_DEPLOY_SCHEDULER

on:
  schedule:
    - cron: '30 21 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://api.vercel.com/v1/integrations/deploy/prj_L2SUoQYCauS60zHwkQA4XNbL0ppl/JYhdyd9COd' \
