# This is a basic workflow to help you get started with Actions

name: THE_WARZONE_REPORT_HOURLY_DEPLOY_SCHEDULER

on:
  schedule:
    - cron: '0 18 * * *'
    - cron: '0 19 * * *'
    - cron: '0 20 * * *'
    - cron: '0 21 * * *'
    - cron: '35 21 * * *'
    - cron: '0 22 * * *'
    - cron: '0 23 * * *'
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://api.vercel.com/v1/integrations/deploy/prj_L2SUoQYCauS60zHwkQA4XNbL0ppl/JYhdyd9COd' \
